-- MySQL Script generated by MySQL Workbench
-- 03/23/21 12:42:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TECHNOLOGY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TECHNOLOGY` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `TECHNOLOGY` ;

-- -----------------------------------------------------
-- Table `TECHNOLOGY`.`Developer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TECHNOLOGY`.`Developer` ;

CREATE TABLE IF NOT EXISTS `TECHNOLOGY`.`Developer` (
  `devID` INT NOT NULL,
  `devName` VARCHAR(45) NULL,
  `companyAddress` VARCHAR(45) NULL,
  `companyTel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`devID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TECHNOLOGY`.`ProductiveTechnology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TECHNOLOGY`.`ProductiveTechnology` ;

CREATE TABLE IF NOT EXISTS `TECHNOLOGY`.`ProductiveTechnology` (
  `techID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `setup` VARCHAR(45) NULL,
  `RRP` VARCHAR(45) NULL,
  `Developer_devID` INT NOT NULL,
  PRIMARY KEY (`techID`),
  INDEX `fk_ProductiveTechnology_Developer_idx` (`Developer_devID` ASC),
  CONSTRAINT `fk_ProductiveTechnology_Developer`
    FOREIGN KEY (`Developer_devID`)
    REFERENCES `TECHNOLOGY`.`Developer` (`devID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TECHNOLOGY`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TECHNOLOGY`.`Employee` ;

CREATE TABLE IF NOT EXISTS `TECHNOLOGY`.`Employee` (
  `employeeID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `jobType` VARCHAR(45) NULL,
  `techniques` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TECHNOLOGY`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TECHNOLOGY`.`Ratings` ;

CREATE TABLE IF NOT EXISTS `TECHNOLOGY`.`Ratings` (
  `techID` INT NOT NULL,
  `employeeID` INT NOT NULL,
  `usage` VARCHAR(45) NULL,
  `scoreRating` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  PRIMARY KEY (`techID`, `employeeID`),
  INDEX `fk_ProductiveTechnology_has_Employee_Employee1_idx` (`employeeID` ASC),
  INDEX `fk_ProductiveTechnology_has_Employee_ProductiveTechnology1_idx` (`techID` ASC),
  CONSTRAINT `fk_ProductiveTechnology_has_Employee_ProductiveTechnology1`
    FOREIGN KEY (`techID`)
    REFERENCES `TECHNOLOGY`.`ProductiveTechnology` (`techID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductiveTechnology_has_Employee_Employee1`
    FOREIGN KEY (`employeeID`)
    REFERENCES `TECHNOLOGY`.`Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
